name = ("Chanachai")
surname = ("Sangsiri")
print("Name :" , name , surname)
nickname = ("Earth")
print("Nick Name :" , nickname)
age = 17
print("Age :" , age)
marksuckabuy = ("Fujimiya Katsuki Sekai")
print("Facebook :" , marksuckabuy)
line = ("earthzyth")
print("Line ID :" , line)
sex = ("Male")
print("Sex :" , sex)
address = ("on the earth")
print("Address :" , address)
hobbies = ("Play games , Listen to music")
print("Hobbie :" , hobbies)
Steam = ("Fujimiya Katsuki Sekai")
print("Steam :" , Steam)
Games = ("warframe")
print("My favorite games :" , Games)
#นายชนะชัย สังข์ศิริ 6/14 8)