print("Name : Chanachai Sangsiri")
print("Nick Name : Earth")
print("Age : 17")
print("Facebook : Fujimiya Katsuki Sekai")
print("Line ID : earthzyth")
print("Sex : Male")
print("Adress : on the earth")
print("Hobbie : Play Games , Listen to music")
print("Steam : Fujimiya Katsuki Sekai")
print("My favorite games : warframe")
#นายชนะชัย สังข์ศิริ 6/14 8)